version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: dislog-training
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=tarcizio
      - POSTGRES_PASSWORD=k9sonwow
      - POSTGRES_DB=dislogtraining
  dbtest:
    image: postgres:latest
    restart: always
    container_name: dislog-training-test
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=tarcizio
      - POSTGRES_PASSWORD=k9sonwow
      - POSTGRES_DB=dislogtrainingtest